title: "URL"
baseline: "Static URL manager and shortener"
baseurl: https://cecil.local/
description: "Static URL manager and shortener, powered by Cecil."
theme:
  - netlify
pages:
  default:
    sitemap:
      published: false
    xsl/atom:
      published: false
    xsl/rss:
      published: false
    xsl/sitemap:
      published: false
  virtual:
    # Apache Rewrite file
    - path: .htaccess
      output: apache_rewrite
output:
  formats:
    apache_rewrite:
      mediatype: 'text/plain'
      extension: ''
  pagetypeformats:
    homepage: html
